# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.3'

# Define services
services:
  # App service
  app-server:
    # Configuration for building the docker image for the service
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "9090:9090" # Forward the exposed port 9090 on the container to port 9090 on the host machine
    restart: always
    depends_on: 
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/file_demo?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      SPRING_DATASOURCE_USERNAME: roshan
      SPRING_DATASOURCE_PASSWORD: password     

  # Database Service (Mysql)
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: file_demo
      MYSQL_USER: roshan
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
 